[2025-04-20T02:39:27.334+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spacex_ml_training_pipeline.train_model manual__2025-04-20T02:34:24.547621+00:00 [queued]>
[2025-04-20T02:39:27.341+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spacex_ml_training_pipeline.train_model manual__2025-04-20T02:34:24.547621+00:00 [queued]>
[2025-04-20T02:39:27.341+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2025-04-20T02:39:27.349+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): train_model> on 2025-04-20 02:34:24.547621+00:00
[2025-04-20T02:39:27.351+0000] {standard_task_runner.py:57} INFO - Started process 263 to run task
[2025-04-20T02:39:27.354+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'spacex_ml_training_pipeline', 'train_model', 'manual__2025-04-20T02:34:24.547621+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/spacex_training_dag.py', '--cfg-path', '/tmp/tmpsd50l_b_']
[2025-04-20T02:39:27.356+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask train_model
[2025-04-20T02:39:27.367+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-20T02:39:27.390+0000] {task_command.py:415} INFO - Running <TaskInstance: spacex_ml_training_pipeline.train_model manual__2025-04-20T02:34:24.547621+00:00 [running]> on host 7d5e8b868ff6
[2025-04-20T02:39:27.432+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gaurav' AIRFLOW_CTX_DAG_ID='spacex_ml_training_pipeline' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-04-20T02:34:24.547621+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-20T02:34:24.547621+00:00'
[2025-04-20T02:39:27.433+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-20T02:39:27.433+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/project/train.py']
[2025-04-20T02:39:27.440+0000] {subprocess.py:86} INFO - Output:
[2025-04-20T02:39:28.007+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-04-20T02:39:28.008+0000] {subprocess.py:93} INFO -   File "/opt/***/project/train.py", line 3, in <module>
[2025-04-20T02:39:28.008+0000] {subprocess.py:93} INFO -     from sklearn import preprocessing
[2025-04-20T02:39:28.008+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'sklearn'
[2025-04-20T02:39:28.049+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-20T02:39:28.059+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-20T02:39:28.062+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=spacex_ml_training_pipeline, task_id=train_model, execution_date=20250420T023424, start_date=20250420T023927, end_date=20250420T023928
[2025-04-20T02:39:28.071+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task train_model (Bash command failed. The command returned a non-zero exit code 1.; 263)
[2025-04-20T02:39:28.077+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-04-20T02:39:28.091+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
