[2025-04-20T02:34:26.040+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spacex_ml_training_pipeline.train_model manual__2025-04-20T02:34:24.547621+00:00 [queued]>
[2025-04-20T02:34:26.045+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spacex_ml_training_pipeline.train_model manual__2025-04-20T02:34:24.547621+00:00 [queued]>
[2025-04-20T02:34:26.045+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-04-20T02:34:26.052+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): train_model> on 2025-04-20 02:34:24.547621+00:00
[2025-04-20T02:34:26.055+0000] {standard_task_runner.py:57} INFO - Started process 189 to run task
[2025-04-20T02:34:26.058+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'spacex_ml_training_pipeline', 'train_model', 'manual__2025-04-20T02:34:24.547621+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/spacex_training_dag.py', '--cfg-path', '/tmp/tmpkzjxmqz0']
[2025-04-20T02:34:26.059+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask train_model
[2025-04-20T02:34:26.070+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-20T02:34:26.102+0000] {task_command.py:415} INFO - Running <TaskInstance: spacex_ml_training_pipeline.train_model manual__2025-04-20T02:34:24.547621+00:00 [running]> on host 7d5e8b868ff6
[2025-04-20T02:34:26.148+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gaurav' AIRFLOW_CTX_DAG_ID='spacex_ml_training_pipeline' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-04-20T02:34:24.547621+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-20T02:34:24.547621+00:00'
[2025-04-20T02:34:26.149+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-20T02:34:26.150+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/project/train.py']
[2025-04-20T02:34:26.155+0000] {subprocess.py:86} INFO - Output:
[2025-04-20T02:34:26.665+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-04-20T02:34:26.666+0000] {subprocess.py:93} INFO -   File "/opt/***/project/train.py", line 3, in <module>
[2025-04-20T02:34:26.666+0000] {subprocess.py:93} INFO -     from sklearn import preprocessing
[2025-04-20T02:34:26.666+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'sklearn'
[2025-04-20T02:34:26.702+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-20T02:34:26.709+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-20T02:34:26.711+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=spacex_ml_training_pipeline, task_id=train_model, execution_date=20250420T023424, start_date=20250420T023426, end_date=20250420T023426
[2025-04-20T02:34:26.719+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task train_model (Bash command failed. The command returned a non-zero exit code 1.; 189)
[2025-04-20T02:34:26.742+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-04-20T02:34:26.752+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
